### ISSUE TITLE
Best practices when developing on a team

### ISSUE THREAD

**Issue by KhalidAdan** [BulletTrainHQ/bullet-train-docker#4]
Hello! 

I'm a developer on a team that has adopted bullet train to manage our feature flags. We currently run bullet train via docker. The question I had was how do you think we should share the flags between developers locally while multiple devs are adding and removing flags.

 It just feels a little weird for devs to have to log in to bullet train locally and create an environment every time they set up / reset their DB or fetch changes from colleagues, so I don't think running the containers locally will work.

One idea I am thinking about is running bullet train in our kubernetes cluster instead of (locally running docker containers) and managing them from there for all of our devs but then we would need an internet connection to develop. 

If you have any ideas or use a specific strategy to solve this problem I'd love to hear it.

**Comment by dabeeeenster** [comment]
We would recommend a single shared instance of the platform just like our SaaS offering.

**Comment by airhorns** [comment]
@dabeeeenster there's a couple downsides to using a shared instance IMO: you have to be online to develop, the test infrastructure and dev infrastructure are coupled to the production infrastructure's uptime, and developer's environments are now linked to each other unless each developer creates and manages their own Bullet Train environment, which was what OP was trying to avoid. 

With the prod infrastructure coupling thing, let's say we self host a bullet train, and it goes down because we misconfigure it. If our CI environment is using the production bullet train instance which is down, our tests may start failing, preventing us from deploying the fix to the thing that is broken. I know that is something very much within our control and we could architect around it, but I think the cleanest architecture would be running a bullet train instance as a background service for the CI infrastructure.

It seems like we can't really do that for testing or for development because the environment IDs aren't predictable or provision-able from config AFAICT.  Because the environment IDs aren't predictable, we either have to hardcode one shared environment ID for all developers to use, which would mean if one dev wanted to test with a flag on, they'd turn it on for all devs, which kind of violates developers expectations around their own environments being sealed off from everyone else's.  Same with the test infrastructure: if you wanted the tests to run with a certain flag state, you'd have to go configure that in the production instance before the tests might pass. It'd be a source of a lot of heisenbugs if you ask me.

is there a way to provision environments with predictable IDs or script provisioning them locally?

**Comment by dabeeeenster** [comment]
These are interesting issues, especially around self hosting. It's not something we've really designed for tho! You can trivially overwrite the environment ID in the database if that would help?

**Comment by airhorns** [comment]
I suppose we could do that, but it feels a little sketchy because if you folks add more caching or change the table schema or anything like that it may break. We'd be coupling to internals of the system instead of the intended public API. And FWIW I think several of the same set of problems occur regardless of self hosting or using the SaaS. 

Would you folks consider adding an environment provisioning API, or better yet, just letting API clients use arbitrary environment keys and manifesting them as they get used? That'd be the easiest API for me to use as a consumer IMO.

**Comment by kyle-ssg** [comment]
There are a few things here that I think are being discussed:

> The question I had was how do you think we should share the flags between developers locally while multiple devs are adding and removing flags.

Environments within a project of a single API instance share flags, if a user creates or removes a flag on a bullet train project it will do so for all environments within the project. This supports the suggestion of using a single API instance.

> It just feels a little weird for devs to have to log in to bullet train locally and create an environment every time they set up / reset their DB or fetch changes from colleagues, so I don't think running the containers locally will work.

You don't have to, we have an API where you can create and destroy Bullet Train environments as part of CI.

> It seems like we can't really do that for testing or for development because the environment IDs aren't predictable or provision-able from config AFAICT. Because the environment IDs aren't predictable, we either have to hardcode one shared environment ID for all developers to use, which would mean if one dev wanted to test with a flag on, they'd turn it on for all devs, which kind of violates developers expectations around their own environments being sealed off from everyone else's.

The first question is "is this an integration test or is this a unit test, i.e. what do you actually want to test?" In both cases however your tests should cover:

- A feature's flag being off
- A feature's flag being on
- If you have default flags, a set of tests for what you'd expect when you do not get a response from Bullet Train.

You do this because flags are dynamic, they can be on or off depending in your environment depending on when the test is run, so you have to mock all cases.

If you then want to do a final integration test against an environment you can then use an actual environment ID and dynamically run tests based on the flag evaluations for that environment, though at that point you're basically just testing the Bullet Train API rather than your own application if you've written the previous tests.

**Comment by airhorns** [comment]
> You don't have to, we have an API where you can create and destroy Bullet Train environments as part of CI.

Ah, amazing. Is that the Admin API? I couldn't find anything in the docs for this but maybe I am just a dumb dumb. 

> You do this because flags are dynamic, they can be on or off depending in your environment depending on when the test is run, so you have to mock all cases.

Is that how most folks end up testing with Bullet Train in the mix is just by mocking the whole thing so they test all the different branches? I get that mocking works great and is borderline required for the tests where you want to be very explicit about the global state that the test is running in. It would also allow us to not have to hit a real instance in the tests if we didn't want to.

**Comment by kyle-ssg** [comment]
I guess given the above to answer provisioning api_keys, I'd ask what benefit that'd give with testing 

> > You don't have to, we have an API where you can create and destroy Bullet Train environments as part of CI.
> 
> Ah, amazing. Is that the Admin API? I couldn't find anything in the docs for this but maybe I am just a dumb dumb.
> 

Yeah, the frontend application uses the exact same API.

> > You do this because flags are dynamic, they can be on or off depending in your environment depending on when the test is run, so you have to mock all cases.
> 
> Is that how most folks end up testing with Bullet Train in the mix is just by mocking the whole thing so they test all the different branches? I get that mocking works great and is borderline required for the tests where you want to be very explicit about the global state that the test is running in. It would also allow us to not have to hit a real instance in the tests if we didn't want to.


Yeah, in the instances I've seen the most important part is to mock the flags to test both whether the flag is on or off. If you don't do this then your tests don't have much value since a flag can be altered immediately after a test. 

Then yes also in combination with this test against an actual environment ID as an integration test without Bullet Train being mocked, though this is basically just double checking the first tests that were written with the actual API. At this point the only reason for these failing should be down to unexpected API responses or perhaps a combination of flags leading to unexpected results.

**Comment by dabeeeenster** [comment]
@airhorns there's documentation about our API here: https://docs.bullet-train.io/api/
